### ISSUE TITLE
Can't figure out how it's working for you so far

### ISSUE THREAD

**Issue by volodymyr-kushnir** [pbazyliuk/BSA-2017-GIT-NEW#1]
Hi, @pbazyliuk, what's up? I saw that you're poking around with GitHub (nothing wrong with that really) and I thought maybe you need an advise of some sort or something.
Як там? Порядок? Бачу вже третій репозиторій, ніяких проблем з цим, але думаю, перепитаю, може підкажу щось.

**Comment by pbazyliuk** [comment]
Привіт! От страюсь шось придумати, бо завдання і технічне і творче=) Як закінчу просив би, якшо можливо було коротке ревью зробити чи немає серйозних недоліків?!=)

**Comment by volodymyr-kushnir** [comment]
@pbazyliuk нема проблем, просто згадуй "@volodymyr-kushnir" там де потрібна порада.

Загалом я б починав з проекту в розділі **Projects** — склав би список завдань, в процесі виконання перетягував би в колонку **In progress**, конвертував би в **Issues** (там є така можливість), впроваджував би функціонал в окремій гілці, коммітив би з повідомленням **"Додано блаблабла (fixes #1)"** — це автоматично закриє issue #1 — і тоді би тягнув картку завдання в колонку **Done** розділу **Projects**.

**Comment by pbazyliuk** [comment]
Володя я шось пропустив=) бо я думав просто в редакторі створити статтю і потім редагувати її і по ходу робити коміти та гілки...  Те що ти написав потрібно робити в GitKraken?!

**Comment by volodymyr-kushnir** [comment]
@pbazyliuk не-не, всьо правильно — в редакторі створити статтю і потім редагувати її і по ходу робити коміти та гілки. GitKraken був просто згаданий як інструмент, яким хлопці могли б перевірити репозиторій, до завдання він відношення не має.

**Comment by volodymyr-kushnir** [comment]
@pbazyliuk та, всьо правильно ти почав. Накидати тобі проблем (в смислі **Issues**) чи зробиш собі сам?

**Comment by pbazyliuk** [comment]
я шось зробив, але не знаю чи правильно закинув, бо чогось тільки по 1 гілці пушив?!

https://github.com/pbazyliuk/BSA-2017-GIT-NEW

**Comment by volodymyr-kushnir** [comment]
чого ж, ось тут https://github.com/pbazyliuk/BSA-2017-GIT-NEW/tree/article-science явно два комміти є

**Comment by pbazyliuk** [comment]
в мене 8 комітів на мастері=)

**Comment by pbazyliuk** [comment]
треба було б щось додати, чи змінити?!

**Comment by volodymyr-kushnir** [comment]
![image](https://cloud.githubusercontent.com/assets/10290626/26278473/18ce2006-3da4-11e7-85cd-52f561515c36.png)
Наразі виглядає отак. Ну я б рекомендував все-таки перейти на Markdown, відтак змінити форматування тощо. Додай мене до **Collaborator**'ів в налаштуваннях репозиторію.

**Comment by pbazyliuk** [comment]
додав до Collaborator'ів, не зрозумів про Markdown?!

**Comment by volodymyr-kushnir** [comment]
@pbazyliuk, секунду...

**Comment by pbazyliuk** [comment]
ок

**Comment by volodymyr-kushnir** [comment]
@pbazyliuk ну вперед, спочатку таску перетягнути в стовпець, потім бренч зробити, потім провести зміни, потім закоммітити, тоді закрити проблему в **Issues**, тоді переставити таску в **Done**. Agile FTW.

**Comment by volodymyr-kushnir** [comment]
@pbazyliuk ось [конвертер](https://domchristie.github.io/to-markdown/) в markdown (сам не юзав, може знайдеш кращий)

**Comment by pbazyliuk** [comment]
Дякую, зараз буду розбиратись!
20 трав. 2017 22:29 "Volodymyr Kushnir" <notifications@github.com> пише:

**Comment by volodymyr-kushnir** [comment]
@pbazyliuk дві таски не в стовпці **Ready**, бо вони блоковані. спочатку треба змінити розширення. як тільки розширення впроваджене, то вони переходять в **Ready**, а тоді по черзі в **Work in progress**. приблизно так воно працює, успіхів.

**Comment by pbazyliuk** [comment]
зробив але не дуже зрозумів як їх відмічати.... я відмітив marked as closed чи це не то?!

**Comment by volodymyr-kushnir** [comment]
@pbazyliuk це ти позначив проблеми. а картки залишились [як були](https://github.com/pbazyliuk/BSA-2017-GIT-NEW/projects/1). я залишив коментар [тут](https://github.com/pbazyliuk/BSA-2017-GIT-NEW/commit/abaee784f52820bbc9562875f88e80388afbbf87) і [тут](https://github.com/pbazyliuk/BSA-2017-GIT-NEW/commit/5737805f4a77d4b6440c5cc9fbe6603197099c12).

Картки в **Projects** — опис проблеми, story, як вони кажуть. Проблеми в **Issues** — спроба описати історію технічно. Тобто одна картка в Project може мати одну або біьше проблем в Issues. Наприклад, "Змінити форматування" в проекті може мати "Переформатувати заголовки" і "Виділити жирним ключові слова" в проблемах.

**Comment by pbazyliuk** [comment]
дякую, зрозумів, чесно не знав шо тут свій трелло є=)))

**Comment by pbazyliuk** [comment]
хотів у тебе ще таку штуку запитати, коли заходиш на пейдж академії то зявляється надпис на екрані, його частинка одна статична, а інша динамічна і змінюється?! яким чином це можна зробити, це якісь додаткові бібліотеки використовуються?!

**Comment by volodymyr-kushnir** [comment]
@pbazyliuk без найменшого поняття, я типу "не в клубі" і доступу до академії зсередини не маю. проте, якщо мова йде про ті хвилі, то це [three.js](https://threejs.org/examples/canvas_particles_waves.html)

**Comment by pbazyliuk** [comment]
Зрозуміло, я мав на увазі надпис вище анімації tree.js, BEST START FOR,
далі текст динамічно змінюється?!
21 трав. 2017 01:09 "Volodymyr Kushnir" <notifications@github.com> пише:

**Comment by volodymyr-kushnir** [comment]
@pbazyliuk на "кодіхауз" було, https://codyhouse.co/gem/css-animated-headlines/, там такого вагонами

**Comment by pbazyliuk** [comment]
дуже дякую!
21 трав. 2017 01:42 "Volodymyr Kushnir" <notifications@github.com> пише:
